name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set build number
        id: version
        run: echo "::set-output name=BUILD_VERSION::v0.${{ github.run_number }}"

      - name: Generate Dockerfile and Entrypoint
        run: |
          cat > Dockerfile <<EOF
          # Use a base image
          FROM azul/zulu-openjdk:17

          # Install necessary packages
          ARG DEBIAN_FRONTEND=noninteractive
          ENV TZ=Etc/UTC
          RUN apt-get install -y tzdata
          RUN apt-get update -y && \
              apt-get install -y git maven && \
              rm -rf /var/lib/apt/lists/*

          # Clone and build the Spigot server
          RUN git clone --branch minimal https://${{ secrets.GH_TOKEN }}@github.com/MineLC/LCSpigot.git /tmp/spigot && \
          cd /tmp/spigot && \
          mvn clean install && \
          mvn clean package

          # Set up the Minecraft server directory
          WORKDIR /minecraft
          RUN cp /tmp/spigot/target/lcspigot-*.jar .

          # Clone and build additional plugins
          RUN git clone https://${{ secrets.GH_TOKEN }}@github.com/MineLC/LC-Commons.git /tmp/commons && \
              cd /tmp/commons && \
              mvn clean install && \
              mvn clean package && \
              cp target/LCCommons-*.jar /tmp/spigot/plugins/

          RUN git clone https://${{ secrets.GH_TOKEN }}@github.com/MineLC/SlimeWorldManager.git /tmp/slime && \
              cd /tmp/slime && \
              mvn clean install && \
              mvn clean package && \
              cp slimeworldmanager-plugin/target/slimeworldmanager-plugin-*-SNAPSHOT-jar-with-dependencies.jar /tmp/spigot/plugins/ && \
              cp slimeworldmanager-classmodifier/target/slimeworldmanager-classmodifier-*-SNAPSHOT.jar /tmp/spigot/

          RUN git clone https://github.com/MineLC/HG-v2.git /tmp/plugin && \
              cd /tmp/plugin && \
              mvn clean package && \
              cp target/hg-*-jar-with-dependencies.jar /tmp/spigot/plugins/

          # Set default environment variables for min memory and memory
          ENV MINMEMORY=4608
          ENV MEMORY=4608

          # Set the default port to 25565
          ENV PORT=25565

          # Expose the port
          EXPOSE 25565

          # Set the command to run the server with the specified memory options
          CMD ["/entrypoint.sh"]
          EOF

          cat > entrypoint.sh <<'EOL'
          #!/bin/bash
          set -euo pipefail

          # Set up the memory options for Java
          JAVA_OPTS="-Xms${MINMEMORY}M -Xmx${MEMORY}M"

          # Run the Minecraft server with the specified memory options and custom port
          java $JAVA_OPTS -javaagent:slimeworldmanager-classmodifier-2.2.0-SNAPSHOT.jar -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar lcspigot-*.jar --port $PORT
          EOL

      - name: Build Docker image
        run: docker build -t my-image .