name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set build number
        id: version
        run: echo "::set-output name=BUILD_VERSION::v0.${{ github.run_number }}"

      - name: Generate Dockerfile
        run: |
          cat > Dockerfile <<EOF
          ARG PORT=25565
          ARG MEMORY=4608
          ARG MINMEMORY=4608

          FROM azul/prime:17

          RUN apt-get update && \\
              apt-get install -y git maven && \\
              rm -rf /var/lib/apt/lists/*

          RUN git clone --branch minimal https://github.com/MineLC/LCSpigot.git /tmp/spigot && \\
              cd /tmp/spigot && \\
              mvn clean package

          WORKDIR /minecraft
          RUN cp /tmp/spigot/target/lcspigot-*.jar .

          RUN java -jar lcspigot-*.jar && \\
              sleep 10 && \\
              screen -S spigot -X stuff "stop^M"

          RUN mv /tmp/spigot .

          RUN git clone https://github.com/MineLC/LC-Commons.git /tmp/commons && \\
              cd /tmp/commons && \\
              mvn clean package && \\
              cp target/LCCommons-1.0-SNAPSHOT.jar /tmp/spigot/plugins/

          RUN git clone https://github.com/MineLC/HG-v2.git /tmp/plugin && \\
              cd /tmp/plugin && \\
              mvn clean package && \\
              cp target/hg-0.0.1-jar-with-dependencies.jar /tmp/spigot/plugins/

          RUN git clone https://github.com/MineLC/SlimeWorldManager.git /tmp/slime && \\
              cd /tmp/slime && \\
              mvn clean package && \\
              cp target/slimeworldmanager-plugin-2.2.0-SNAPSHOT-jar-with-dependencies.jar /tmp/spigot/plugins/ && \\
              cp target/slimeworldmanager-classmodifier-2.2.0-SNAPSHOT.jar /tmp/spigot/

          EXPOSE $PORT

          CMD ["java", "-Xms${MINMEMORY}M", "-Xmx${MEMORY}M", "-javaagent:slimeworldmanager-classmodifier-2.2.0-SNAPSHOT.jar", "-XX:+UseG1GC", "-XX:+ParallelRefProcEnabled", "-XX:MaxGCPauseMillis=200", "-XX:+UnlockExperimentalVMOptions", "-XX:+DisableExplicitGC", "-XX:+AlwaysPreTouch", "-XX:G1HeapWastePercent=5", "-XX:G1MixedGCCountTarget=4", "-XX:InitiatingHeapOccupancyPercent=15", "-XX:G1MixedGCLiveThresholdPercent=90", "-XX:G1RSetUpdatingPauseTimePercent=5", "-XX:SurvivorRatio=32", "-XX:+PerfDisableSharedMem", "-XX:MaxTenuringThreshold=1", "-Dusing.aikars.flags=https://mcflags.emc.gs", "-Daikars.new.flags=true", "-XX:G1NewSizePercent=30", "-XX:G1MaxNewSizePercent=40", "-XX:G1HeapRegionSize=8M", "-XX:G1ReservePercent=20", "-jar", "lcspigot-*.jar"]
          EOF

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/ToshioDev/hg-server:${{ steps.version.outputs.BUILD_VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}